### ISSUE TITLE
Crash setting server 

### ISSUE THREAD

**Issue by danger67** [davidumoru/ts-backend#1]
May server crash re open command

**Comment by davidumoru** [comment]
Hi @danger67

Thanks for reporting the server crash issue. I'd like to help you troubleshoot it further.

To get a better understanding of the problem, could you please provide some additional details?

- Crash Details: Can you describe the steps you were taking when the server crashed? Were you running a specific command, or did it crash during setup?
- Error Messages: Did you see any error messages displayed in the terminal when the crash happened? If so, please copy and paste the exact error messages here.
- "Re-open command": Could you clarify what you meant by "re-open command"? Were you referring to restarting the server or re-running a specific setup command?
